### ISSUE TITLE
Game details- comments section and rating

### ISSUE THREAD

**Issue by patricksommer** [elenirotsides/Team-418#37]
Details TBD

**Comment by elenirotsides** [comment]
Frontend functionality and route 
maybe: review component inside of game.js

**Comment by JordanH821** [comment]
basic start to this in jordan/reviews branch

**Comment by elenirotsides** [comment]
@JordanH821 Should I close this or is there more that needs to be done? If there's more, can you write a few bullet points in the comments here when you can? Thanks!

**Comment by elenirotsides** [comment]
I'm going to take the liberty of closing this since its done
