### ISSUE TITLE
Need a descriptive README

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Team-418#84]
We should make sure to include any tokens Prof/TA might need to run our application in addition to directions on how to run our application

**Comment by JordanH821** [comment]
Currently needed:
- .env
- googleInfo.json
- ImageMagick requirement ***on system path***
- Redis running on standard port
-

**Comment by JordanH821** [comment]
closes with #115

**Comment by arandomdude24** [comment]
Closing this because I think Jordan's update covers everything the readme needs
